services:
  dadou-robot:
    container_name: dadou-robot-container
    image: dadouuu/dadou-robot-arm:latest
    build:
      context: ../../..
      dockerfile: conf/docker/arm/Dockerfile-arm
    environment:
      #- DISPLAY=${DISPLAY}
      - ALSA_CARD=0
    #ports:
    #  - "80:80"
    #  - "8000-9000:8000-9000"
    network_mode: "host"

    volumes:
      #- /tmp/.X11-unix:/tmp/.X11-unix
      - ../../../conf:/home/ros2_ws/src/robot/conf
      - ../../../robot:/home/ros2_ws/src/robot/robot
      - ../../../dadou_utils_ros:/home/ros2_ws/src/robot/dadou_utils_ros
      - ../../../json:/home/ros2_ws/src/robot/json
      - ../../../medias:/home/ros2_ws/src/robot/medias
      - ../../../../robot_bringup:/home/ros2_ws/src/robot_bringup
      - ../../../../robot_interfaces:/home/ros2_ws/src/robot_interfaces
      - ../../../../../build:/home/ros2_ws/build
      - ../../../../../install:/home/ros2_ws/install
      - ../../../../../log:/home/ros2_ws/log
      - ../../../conf/ros2/setup.py:/home/ros2_ws/src/robot/setup.py
      - ../../../conf/ros2/package.xml:/home/ros2_ws/src/robot/package.xml
      - /dev:/dev
      - /dev/snd:/dev/snd
    #  - /dev/null:/folder/fileToBeExcluded
    #accès device ACMO gpio serial by id disque etc ...
    privileged: true
 #   devices:
 #    - /dev
