services:
  dadou-control:
    container_name: dadou-robot-container
    image: dadouuu/dadou-robot-arm:latest
    build:
      context: ../../..
      dockerfile: conf/docker/arm/Dockerfile-arm
    environment:
      - DISPLAY=${DISPLAY}
      - ALSA_CARD=0
    #ports:
    #  - "80:80"
    #  - "8000-9000:8000-9000"
    network_mode: "host"

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /root/ros2_ws/src/robot/conf:/home/ros2_ws/src/robot/conf
      - /root/ros2_ws/src/robot/robot:/home/ros2_ws/src/robot/robot
      - /root/ros2_ws/src/robot/dadou_utils_ros:/home/ros2_ws/src/robot/dadou_utils_ros
      - /root/ros2_ws/src/robot/json:/home/ros2_ws/src/robot/json
      - /root/ros2_ws/src/robot/medias:/home/ros2_ws/src/robot/medias
      - /root/ros2_ws/src/robot_bringup:/home/ros2_ws/src/robot_bringup
      - /root/ros2_ws/src/robot_interfaces:/home/ros2_ws/src/robot_interfaces
      - /root/ros2_ws/log:/home/ros2_ws/log
      - /root/ros2_ws/src/robot/setup.py:/home/ros2_ws/src/robot/setup.py
      - /dev:/dev
      - /dev/snd:/dev/snd
    #  - /dev/null:/folder/fileToBeExcluded
    #accès device ACMO gpio serial by id disque etc ...
    privileged: true
 #   devices:
 #    - /dev
